### ISSUE TITLE
Traffic log crashes when running in a multiple profile environment

### ISSUE THREAD

**Issue by anthonyMc11** [TrackerControl/tracker-control-android#442]
Tracker control direct from Github

**Describe the bug**
I am running Tracker control on a multi profile android phone. On the root profile, Tracker control works flawlessly. However on a secondary profile, the app crashes when viewing the traffic log

**To Reproduce**
1. Create a device with multiple profile
2. log in to the non owner profile (ie not user 0)
3. Enable VPN
4.  Enable Traffic logging
5. Wait for log from user 0

When this happens, the following exception is thrown ( I've shortened the stack track):
STACK_TRACE=java.lang.SecurityException: getPackagesForUid: UID 1010154 requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS to access user 0.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3240)
	at android.os.Parcel.createException(Parcel.java:3224)
	at android.os.Parcel.readException(Parcel.java:3200)
	at android.os.Parcel.readException(Parcel.java:3142)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackagesForUid(IPackageManager.java:5176)
	at android.app.ApplicationPackageManager$3.recompute(ApplicationPackageManager.java:1148)
	at android.app.ApplicationPackageManager$3.recompute(ApplicationPackageManager.java:1142)
	at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:1046)
	at android.app.ApplicationPackageManager.getPackagesForUid(ApplicationPackageManager.java:1161)
	at eu.faircode.netguard.AdapterLog.bindView(AdapterLog.java:215)
	at android.widget.CursorAdapter.getView(CursorAdapter.java:296)

As you can see there is a security warning.

**Comment by anthonyMc11** [comment]
I've raised a pull request to address this issue

**Comment by anthonyMc11** [comment]
I've closed the PR as this was an issue in NetGuard, pulling the latest netguard would resolve this bug

https://github.com/M66B/NetGuard/commit/d2fd678dbaac5e8d5d251a17edda34d6407cba56

**Comment by kasnder** [comment]
Thanks!

**Comment by kasnder** [comment]
Synced now
